// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.countCommitsByRepoIDStmt, err = db.PrepareContext(ctx, countCommitsByRepoID); err != nil {
		return nil, fmt.Errorf("error preparing query CountCommitsByRepoID: %w", err)
	}
	if q.createCommitStmt, err = db.PrepareContext(ctx, createCommit); err != nil {
		return nil, fmt.Errorf("error preparing query CreateCommit: %w", err)
	}
	if q.createRepositoryStmt, err = db.PrepareContext(ctx, createRepository); err != nil {
		return nil, fmt.Errorf("error preparing query CreateRepository: %w", err)
	}
	if q.deleteRepositoryStmt, err = db.PrepareContext(ctx, deleteRepository); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteRepository: %w", err)
	}
	if q.getCommitStmt, err = db.PrepareContext(ctx, getCommit); err != nil {
		return nil, fmt.Errorf("error preparing query GetCommit: %w", err)
	}
	if q.getRepositoryStmt, err = db.PrepareContext(ctx, getRepository); err != nil {
		return nil, fmt.Errorf("error preparing query GetRepository: %w", err)
	}
	if q.getRepositoryByFullNameStmt, err = db.PrepareContext(ctx, getRepositoryByFullName); err != nil {
		return nil, fmt.Errorf("error preparing query GetRepositoryByFullName: %w", err)
	}
	if q.getTopCommitAuthorsStmt, err = db.PrepareContext(ctx, getTopCommitAuthors); err != nil {
		return nil, fmt.Errorf("error preparing query GetTopCommitAuthors: %w", err)
	}
	if q.listCommitsByRepoIDStmt, err = db.PrepareContext(ctx, listCommitsByRepoID); err != nil {
		return nil, fmt.Errorf("error preparing query ListCommitsByRepoID: %w", err)
	}
	if q.listRepositoriesStmt, err = db.PrepareContext(ctx, listRepositories); err != nil {
		return nil, fmt.Errorf("error preparing query ListRepositories: %w", err)
	}
	if q.updateRepositoryStmt, err = db.PrepareContext(ctx, updateRepository); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateRepository: %w", err)
	}
	if q.updateRepositoryLastSyncedAtStmt, err = db.PrepareContext(ctx, updateRepositoryLastSyncedAt); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateRepositoryLastSyncedAt: %w", err)
	}
	if q.updateRepositorySyncFromDateStmt, err = db.PrepareContext(ctx, updateRepositorySyncFromDate); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateRepositorySyncFromDate: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.countCommitsByRepoIDStmt != nil {
		if cerr := q.countCommitsByRepoIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countCommitsByRepoIDStmt: %w", cerr)
		}
	}
	if q.createCommitStmt != nil {
		if cerr := q.createCommitStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createCommitStmt: %w", cerr)
		}
	}
	if q.createRepositoryStmt != nil {
		if cerr := q.createRepositoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createRepositoryStmt: %w", cerr)
		}
	}
	if q.deleteRepositoryStmt != nil {
		if cerr := q.deleteRepositoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteRepositoryStmt: %w", cerr)
		}
	}
	if q.getCommitStmt != nil {
		if cerr := q.getCommitStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCommitStmt: %w", cerr)
		}
	}
	if q.getRepositoryStmt != nil {
		if cerr := q.getRepositoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRepositoryStmt: %w", cerr)
		}
	}
	if q.getRepositoryByFullNameStmt != nil {
		if cerr := q.getRepositoryByFullNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRepositoryByFullNameStmt: %w", cerr)
		}
	}
	if q.getTopCommitAuthorsStmt != nil {
		if cerr := q.getTopCommitAuthorsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTopCommitAuthorsStmt: %w", cerr)
		}
	}
	if q.listCommitsByRepoIDStmt != nil {
		if cerr := q.listCommitsByRepoIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCommitsByRepoIDStmt: %w", cerr)
		}
	}
	if q.listRepositoriesStmt != nil {
		if cerr := q.listRepositoriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listRepositoriesStmt: %w", cerr)
		}
	}
	if q.updateRepositoryStmt != nil {
		if cerr := q.updateRepositoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateRepositoryStmt: %w", cerr)
		}
	}
	if q.updateRepositoryLastSyncedAtStmt != nil {
		if cerr := q.updateRepositoryLastSyncedAtStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateRepositoryLastSyncedAtStmt: %w", cerr)
		}
	}
	if q.updateRepositorySyncFromDateStmt != nil {
		if cerr := q.updateRepositorySyncFromDateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateRepositorySyncFromDateStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                               DBTX
	tx                               *sql.Tx
	countCommitsByRepoIDStmt         *sql.Stmt
	createCommitStmt                 *sql.Stmt
	createRepositoryStmt             *sql.Stmt
	deleteRepositoryStmt             *sql.Stmt
	getCommitStmt                    *sql.Stmt
	getRepositoryStmt                *sql.Stmt
	getRepositoryByFullNameStmt      *sql.Stmt
	getTopCommitAuthorsStmt          *sql.Stmt
	listCommitsByRepoIDStmt          *sql.Stmt
	listRepositoriesStmt             *sql.Stmt
	updateRepositoryStmt             *sql.Stmt
	updateRepositoryLastSyncedAtStmt *sql.Stmt
	updateRepositorySyncFromDateStmt *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                               tx,
		tx:                               tx,
		countCommitsByRepoIDStmt:         q.countCommitsByRepoIDStmt,
		createCommitStmt:                 q.createCommitStmt,
		createRepositoryStmt:             q.createRepositoryStmt,
		deleteRepositoryStmt:             q.deleteRepositoryStmt,
		getCommitStmt:                    q.getCommitStmt,
		getRepositoryStmt:                q.getRepositoryStmt,
		getRepositoryByFullNameStmt:      q.getRepositoryByFullNameStmt,
		getTopCommitAuthorsStmt:          q.getTopCommitAuthorsStmt,
		listCommitsByRepoIDStmt:          q.listCommitsByRepoIDStmt,
		listRepositoriesStmt:             q.listRepositoriesStmt,
		updateRepositoryStmt:             q.updateRepositoryStmt,
		updateRepositoryLastSyncedAtStmt: q.updateRepositoryLastSyncedAtStmt,
		updateRepositorySyncFromDateStmt: q.updateRepositorySyncFromDateStmt,
	}
}
