// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"database/sql"
	"time"
)

type Commit struct {
	Sha         string    `json:"sha"`
	RepoID      int64     `json:"repo_id"`
	AuthorName  string    `json:"author_name"`
	AuthorEmail string    `json:"author_email"`
	CommitDate  time.Time `json:"commit_date"`
	Message     string    `json:"message"`
	HtmlUrl     string    `json:"html_url"`
}

type Repository struct {
	ID              int64          `json:"id"`
	Name            string         `json:"name"`
	FullName        string         `json:"full_name"`
	Description     sql.NullString `json:"description"`
	Url             string         `json:"url"`
	Language        sql.NullString `json:"language"`
	ForksCount      sql.NullInt64  `json:"forks_count"`
	StargazersCount sql.NullInt64  `json:"stargazers_count"`
	OpenIssuesCount sql.NullInt64  `json:"open_issues_count"`
	WatchersCount   sql.NullInt64  `json:"watchers_count"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	LastSyncedAt    sql.NullTime   `json:"last_synced_at"`
	SyncFromDate    sql.NullTime   `json:"sync_from_date"`
}
