// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountCommitsByRepoID(ctx context.Context, repoID int64) (int64, error)
	CreateCommit(ctx context.Context, arg CreateCommitParams) error
	CreateRepository(ctx context.Context, arg CreateRepositoryParams) (sql.Result, error)
	DeleteRepository(ctx context.Context, id int64) error
	GetCommit(ctx context.Context, sha string) (Commit, error)
	GetRepository(ctx context.Context, id int64) (Repository, error)
	GetRepositoryByFullName(ctx context.Context, fullName string) (Repository, error)
	GetTopCommitAuthors(ctx context.Context, arg GetTopCommitAuthorsParams) ([]GetTopCommitAuthorsRow, error)
	ListCommitsByRepoID(ctx context.Context, arg ListCommitsByRepoIDParams) ([]Commit, error)
	ListRepositories(ctx context.Context) ([]Repository, error)
	UpdateRepository(ctx context.Context, arg UpdateRepositoryParams) error
	UpdateRepositoryLastSyncedAt(ctx context.Context, arg UpdateRepositoryLastSyncedAtParams) error
	UpdateRepositorySyncFromDate(ctx context.Context, arg UpdateRepositorySyncFromDateParams) error
}

var _ Querier = (*Queries)(nil)
