// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: repo.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countCommitsByRepoID = `-- name: CountCommitsByRepoID :one
SELECT COUNT(*) FROM commits WHERE repo_id = ?
`

func (q *Queries) CountCommitsByRepoID(ctx context.Context, repoID int64) (int64, error) {
	row := q.queryRow(ctx, q.countCommitsByRepoIDStmt, countCommitsByRepoID, repoID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCommit = `-- name: CreateCommit :exec
INSERT INTO commits (
    sha, repo_id, author_name, author_email, 
    commit_date, message, html_url
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
`

type CreateCommitParams struct {
	Sha         string    `json:"sha"`
	RepoID      int64     `json:"repo_id"`
	AuthorName  string    `json:"author_name"`
	AuthorEmail string    `json:"author_email"`
	CommitDate  time.Time `json:"commit_date"`
	Message     string    `json:"message"`
	HtmlUrl     string    `json:"html_url"`
}

func (q *Queries) CreateCommit(ctx context.Context, arg CreateCommitParams) error {
	_, err := q.exec(ctx, q.createCommitStmt, createCommit,
		arg.Sha,
		arg.RepoID,
		arg.AuthorName,
		arg.AuthorEmail,
		arg.CommitDate,
		arg.Message,
		arg.HtmlUrl,
	)
	return err
}

const createRepository = `-- name: CreateRepository :execresult
INSERT INTO repositories (
    name, full_name, description, url, language, 
    forks_count, stargazers_count, open_issues_count, 
    watchers_count, created_at, updated_at, last_synced_at, sync_from_date
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateRepositoryParams struct {
	Name            string         `json:"name"`
	FullName        string         `json:"full_name"`
	Description     sql.NullString `json:"description"`
	Url             string         `json:"url"`
	Language        sql.NullString `json:"language"`
	ForksCount      sql.NullInt64  `json:"forks_count"`
	StargazersCount sql.NullInt64  `json:"stargazers_count"`
	OpenIssuesCount sql.NullInt64  `json:"open_issues_count"`
	WatchersCount   sql.NullInt64  `json:"watchers_count"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	LastSyncedAt    sql.NullTime   `json:"last_synced_at"`
	SyncFromDate    sql.NullTime   `json:"sync_from_date"`
}

func (q *Queries) CreateRepository(ctx context.Context, arg CreateRepositoryParams) (sql.Result, error) {
	return q.exec(ctx, q.createRepositoryStmt, createRepository,
		arg.Name,
		arg.FullName,
		arg.Description,
		arg.Url,
		arg.Language,
		arg.ForksCount,
		arg.StargazersCount,
		arg.OpenIssuesCount,
		arg.WatchersCount,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastSyncedAt,
		arg.SyncFromDate,
	)
}

const deleteRepository = `-- name: DeleteRepository :exec
DELETE FROM repositories WHERE id = ?
`

func (q *Queries) DeleteRepository(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteRepositoryStmt, deleteRepository, id)
	return err
}

const getCommit = `-- name: GetCommit :one
SELECT sha, repo_id, author_name, author_email, commit_date, message, html_url FROM commits WHERE sha = ? LIMIT 1
`

func (q *Queries) GetCommit(ctx context.Context, sha string) (Commit, error) {
	row := q.queryRow(ctx, q.getCommitStmt, getCommit, sha)
	var i Commit
	err := row.Scan(
		&i.Sha,
		&i.RepoID,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.CommitDate,
		&i.Message,
		&i.HtmlUrl,
	)
	return i, err
}

const getRepository = `-- name: GetRepository :one
SELECT id, name, full_name, description, url, language, forks_count, stargazers_count, open_issues_count, watchers_count, created_at, updated_at, last_synced_at, sync_from_date FROM repositories WHERE id = ? LIMIT 1
`

func (q *Queries) GetRepository(ctx context.Context, id int64) (Repository, error) {
	row := q.queryRow(ctx, q.getRepositoryStmt, getRepository, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FullName,
		&i.Description,
		&i.Url,
		&i.Language,
		&i.ForksCount,
		&i.StargazersCount,
		&i.OpenIssuesCount,
		&i.WatchersCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSyncedAt,
		&i.SyncFromDate,
	)
	return i, err
}

const getRepositoryByFullName = `-- name: GetRepositoryByFullName :one
SELECT id, name, full_name, description, url, language, forks_count, stargazers_count, open_issues_count, watchers_count, created_at, updated_at, last_synced_at, sync_from_date FROM repositories WHERE full_name = ? LIMIT 1
`

func (q *Queries) GetRepositoryByFullName(ctx context.Context, fullName string) (Repository, error) {
	row := q.queryRow(ctx, q.getRepositoryByFullNameStmt, getRepositoryByFullName, fullName)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FullName,
		&i.Description,
		&i.Url,
		&i.Language,
		&i.ForksCount,
		&i.StargazersCount,
		&i.OpenIssuesCount,
		&i.WatchersCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSyncedAt,
		&i.SyncFromDate,
	)
	return i, err
}

const getTopCommitAuthors = `-- name: GetTopCommitAuthors :many
SELECT 
    author_name, 
    author_email, 
    COUNT(*) as commit_count
FROM commits
WHERE repo_id = ?
GROUP BY author_name, author_email
ORDER BY commit_count DESC
LIMIT ?
`

type GetTopCommitAuthorsParams struct {
	RepoID int64 `json:"repo_id"`
	Limit  int64 `json:"limit"`
}

type GetTopCommitAuthorsRow struct {
	AuthorName  string `json:"author_name"`
	AuthorEmail string `json:"author_email"`
	CommitCount int64  `json:"commit_count"`
}

func (q *Queries) GetTopCommitAuthors(ctx context.Context, arg GetTopCommitAuthorsParams) ([]GetTopCommitAuthorsRow, error) {
	rows, err := q.query(ctx, q.getTopCommitAuthorsStmt, getTopCommitAuthors, arg.RepoID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopCommitAuthorsRow
	for rows.Next() {
		var i GetTopCommitAuthorsRow
		if err := rows.Scan(&i.AuthorName, &i.AuthorEmail, &i.CommitCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommitsByRepoID = `-- name: ListCommitsByRepoID :many
SELECT sha, repo_id, author_name, author_email, commit_date, message, html_url FROM commits 
WHERE repo_id = ? 
ORDER BY commit_date DESC
LIMIT ? OFFSET ?
`

type ListCommitsByRepoIDParams struct {
	RepoID int64 `json:"repo_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListCommitsByRepoID(ctx context.Context, arg ListCommitsByRepoIDParams) ([]Commit, error) {
	rows, err := q.query(ctx, q.listCommitsByRepoIDStmt, listCommitsByRepoID, arg.RepoID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Commit
	for rows.Next() {
		var i Commit
		if err := rows.Scan(
			&i.Sha,
			&i.RepoID,
			&i.AuthorName,
			&i.AuthorEmail,
			&i.CommitDate,
			&i.Message,
			&i.HtmlUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositories = `-- name: ListRepositories :many
SELECT id, name, full_name, description, url, language, forks_count, stargazers_count, open_issues_count, watchers_count, created_at, updated_at, last_synced_at, sync_from_date FROM repositories ORDER BY last_synced_at DESC
`

func (q *Queries) ListRepositories(ctx context.Context) ([]Repository, error) {
	rows, err := q.query(ctx, q.listRepositoriesStmt, listRepositories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FullName,
			&i.Description,
			&i.Url,
			&i.Language,
			&i.ForksCount,
			&i.StargazersCount,
			&i.OpenIssuesCount,
			&i.WatchersCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastSyncedAt,
			&i.SyncFromDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRepository = `-- name: UpdateRepository :exec
UPDATE repositories SET
    name = ?,
    description = ?,
    url = ?,
    language = ?,
    forks_count = ?,
    stargazers_count = ?,
    open_issues_count = ?,
    watchers_count = ?,
    updated_at = ?
WHERE full_name = ?
`

type UpdateRepositoryParams struct {
	Name            string         `json:"name"`
	Description     sql.NullString `json:"description"`
	Url             string         `json:"url"`
	Language        sql.NullString `json:"language"`
	ForksCount      sql.NullInt64  `json:"forks_count"`
	StargazersCount sql.NullInt64  `json:"stargazers_count"`
	OpenIssuesCount sql.NullInt64  `json:"open_issues_count"`
	WatchersCount   sql.NullInt64  `json:"watchers_count"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	FullName        string         `json:"full_name"`
}

func (q *Queries) UpdateRepository(ctx context.Context, arg UpdateRepositoryParams) error {
	_, err := q.exec(ctx, q.updateRepositoryStmt, updateRepository,
		arg.Name,
		arg.Description,
		arg.Url,
		arg.Language,
		arg.ForksCount,
		arg.StargazersCount,
		arg.OpenIssuesCount,
		arg.WatchersCount,
		arg.UpdatedAt,
		arg.FullName,
	)
	return err
}

const updateRepositoryLastSyncedAt = `-- name: UpdateRepositoryLastSyncedAt :exec
UPDATE repositories SET last_synced_at = ? WHERE id = ?
`

type UpdateRepositoryLastSyncedAtParams struct {
	LastSyncedAt sql.NullTime `json:"last_synced_at"`
	ID           int64        `json:"id"`
}

func (q *Queries) UpdateRepositoryLastSyncedAt(ctx context.Context, arg UpdateRepositoryLastSyncedAtParams) error {
	_, err := q.exec(ctx, q.updateRepositoryLastSyncedAtStmt, updateRepositoryLastSyncedAt, arg.LastSyncedAt, arg.ID)
	return err
}

const updateRepositorySyncFromDate = `-- name: UpdateRepositorySyncFromDate :exec
UPDATE repositories SET sync_from_date = ? WHERE id = ?
`

type UpdateRepositorySyncFromDateParams struct {
	SyncFromDate sql.NullTime `json:"sync_from_date"`
	ID           int64        `json:"id"`
}

func (q *Queries) UpdateRepositorySyncFromDate(ctx context.Context, arg UpdateRepositorySyncFromDateParams) error {
	_, err := q.exec(ctx, q.updateRepositorySyncFromDateStmt, updateRepositorySyncFromDate, arg.SyncFromDate, arg.ID)
	return err
}
